- assert:
    that:
      - user_name is defined
      - systemd_option is defined

- block:
  - name: Setup | Create yb-controller logs directory
    file:
      path: "{{ ybc_logs_dir }}"
      state: directory
      mode: 0755
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: Remove existing ybc conf file
    file:
      path: "{{ ybc_conf_file }}"
      state: absent
    tags:
    - override_gflags
    when: ybc_flags is defined

  - name: Configure | Set ybc flags
    lineinfile:
      dest: "{{ ybc_conf_file }}"
      regexp: "^--{{ item.key }}=(.*)"
      line: "--{{item.key}}={{item.value}}"
      create: yes
    with_dict: "{{ ybc_flags }}"
    tags:
    - override_gflags
    when: ybc_flags is defined

- block:
  # Cronjob approach for starting yb-controller
  - name: Setup cron to check liveness of yb-controller
    cron:
      name: "Check liveness of yb-controller"
      minute: "*/1"
      user: "{{ user_name }}"
      job: >
        {{ yb_bin_dir }}/yb-server-ctl.sh yb-controller cron-check ||
        {{ yb_bin_dir }}/yb-server-ctl.sh yb-controller start
    register: cron_result
    failed_when:
      - cron_result is failed
      - cloud_type != "onprem"
    when: not systemd_option
    tags: yb-prebuilt-ami

- block:
  # Remove old cron job and its tasks that start yb-controller
  - name: Remove old cron job that starts yb-controller (for upgrades)
    cron:
      name: "Check liveness of yb-controller"
      user: "yugabyte"
      state: absent

  - name: User mode systemd
    block:
    - name: Stop existing running yb-controller
      systemd:
        name: yb-controller
        state: stopped
        scope: user

    - name: Reload systemd user daemon
      systemd:
        daemon_reload: yes
        scope: user

    # User units need to be linked if waiting on system units
    - name: Link network-online.target
      shell:
        cmd: "systemctl --user link /lib/systemd/system/network-online.target"

    - name: Start network-online.target
      systemd:
        name: network-online.target
        state: started
        enabled: yes
        scope: user

    - name: Enabling and starting yb-controller
      systemd:
        name: yb-controller
        state: started
        enabled: yes
        scope: user

  - name: System (RHEL7) systemd units
    block:
    - name: Stop existing running yb-controller
      shell:
        cmd: "sudo systemctl stop yb-controller"

    # Systemd daemon-reload for yb-controller service files
    - name: Perform daemon-reload for the new services
      shell:
        cmd: "sudo systemctl daemon-reload"

    - name: Enable yb-controller service
      shell:
        cmd: "sudo systemctl enable yb-controller"

    - name: Run yb-controller.service to start the yb-controller
      shell:
        cmd: "sudo systemctl start yb-controller"
  tags:
    - override_gflags
    - systemd_upgrade
  when: systemd_option
