# Copyright (c) Yugabyte, Inc.
#
# To analyze (without uploading to Fossa) -- for local debugging:
# fossa analyze --debug --output
#
# To analyze and upload dependencies:
# fossa analyze --debug

version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: git@github.com:yugabyte/yugabyte-db.git
analyze:
  modules:
    - name: Yugabyte RPC Client
      type: mvn
      target: pom.xml
      path: java
      options:
        cmd: |
          set -euo pipefail -x
          mvn --batch-mode dependency:tree
    - name: PostgreSQL
      type: raw
      target: src/postgres
    - name: YugabyteDB
      type: raw
      target: src/yb
