# This file determines the jobs that we run in this branch on Jenkins.
# Default architecture is x86_64
jobs:
  - os: alma8
    compiler: clang12
    build_type: asan
    release_artifact: false

  - os: centos7
    compiler: clang7
    build_type: tsan
    release_artifact: false

  - os: centos7
    compiler: clang11
    build_type: debug
    release_artifact: false

  - os: alma8
    compiler: clang12
    build_type: release
    release_artifact: true

  - os: centos8
    compiler: clang11
    build_type: release
    architecture: aarch64
    release_artifact: true

  - os: centos8
    compiler: clang11
    build_type: debug
    architecture: aarch64
    release_artifact: false

  - os: centos7
    compiler: gcc5
    build_type: debug
    release_artifact: false

  - os: centos7
    compiler: gcc5
    build_type: release
    release_artifact: false

  - os: alma8
    compiler: gcc9
    build_type: debug
    release_artifact: false

  - os: macos
    compiler: clang
    build_type: debug
    release_artifact: false

  - os: macos
    compiler: clang
    build_type: release
    release_artifact: true

  - os: ubuntu20.04
    compiler: gcc9
    build_type: debug
    release_artifact: false
