# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: Ensure we have the proper vars
  assert:
    that:
      - cloud_type is defined
      - mount_points is defined
      - systemd_option is defined
      - pg_max_mem_mb is defined
      - use_chrony is defined

- block:
  - name: Install and configure chrony with given server list
    include_role:
      name: ansible-chrony
    vars:
      chrony_server: # Necessary to remove default
      chrony_server_list: "{{ ntp_servers }}"
    when: ntp_servers is defined
  - name: Install and configure chrony to cloud defaults
    block:
    - name: Set up default GCP NTP configuration
      include_role:
        name: ansible-chrony
      vars:
        chrony_server: "metadata.google.internal iburst minpoll 4 maxpoll 4"
      when: "{{ cloud_type == 'gcp' }}"
    - name: Set up default AWS NTP configuration
      include_role:
        name: ansible-chrony
      vars:
        chrony_server: "169.254.169.123 iburst minpoll 4 maxpoll 4"
      when: "{{ cloud_type == 'aws' }}"
    - name: Set up default Azure NTP configuratoin
      include_role:
        name: ansible-chrony
      vars:
        chrony_server: # Necessary to remove default
        chrony_azure_refclock: true
      when: "{{ cloud_type == 'azu' }}"
    when: ntp_servers is not defined
  - name: Force date/time synchronization with chrony
    become: yes
    become_method: sudo
    shell: chronyc makestep
  when: use_chrony
  tags: yb-prebuilt-ami

- name: Provision | Set swappiness off
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
  tags: yb-prebuilt-ami

- name: Provision | Create core dump kernel pattern
  sysctl:
    name: kernel.core_pattern
    value: "{{ yb_home_dir }}/cores/core_%e.%p"
    state: present
  tags: yb-prebuilt-ami

- name: Provision | Ensure proper permissions for mount paths.
  file:
    mode: 0755
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    recurse: yes
  with_items: "{{ mount_points.split(',') }}"

- include_tasks: "setup-cgroup.yml"
  # setting up cgroup on YB DB nodes requires installing additional packages from external repos.
  when: not air_gap and pg_max_mem_mb > 0
  tags: yb-prebuilt-ami

# Give yugabyte user sudo access to start/stop/restart master and tserver
- name: Add yugabyte sudo user without password for metric collection operations
  lineinfile:
    dest: /etc/sudoers.d/yugabyte-metrics
    line: 'yugabyte ALL=(ALL:ALL) NOPASSWD: /usr/bin/journalctl -k --since 10min\ ago'
    create: yes
    state: present
    mode: 0440
    validate: 'visudo -cf %s'
  tags: yb-prebuilt-ami

- block:
  # Give yugabyte user sudo access to start/stop/restart master and tserver
  - name: Add yugabyte sudo user without password
    lineinfile:
      dest: /etc/sudoers.d/yugabyte
      line: 'yugabyte ALL=(ALL:ALL) NOPASSWD: /bin/systemctl start yb-master,
            /bin/systemctl stop yb-master,
            /bin/systemctl restart yb-master,
            /bin/systemctl enable yb-master,
            /bin/systemctl disable yb-master,
            /bin/systemctl start yb-tserver,
            /bin/systemctl stop yb-tserver,
            /bin/systemctl restart yb-tserver,
            /bin/systemctl enable yb-tserver,
            /bin/systemctl disable yb-tserver,
            /bin/systemctl start yb-zip_purge_yb_logs.timer,
            /bin/systemctl stop yb-zip_purge_yb_logs.timer,
            /bin/systemctl restart yb-zip_purge_yb_logs.timer,
            /bin/systemctl enable yb-zip_purge_yb_logs.timer,
            /bin/systemctl disable yb-zip_purge_yb_logs.timer,
            /bin/systemctl start yb-clean_cores.timer,
            /bin/systemctl stop yb-clean_cores.timer,
            /bin/systemctl restart yb-clean_cores.timer,
            /bin/systemctl enable yb-clean_cores.timer,
            /bin/systemctl disable yb-clean_cores.timer,
            /bin/systemctl start yb-collect_metrics.timer,
            /bin/systemctl stop yb-collect_metrics.timer,
            /bin/systemctl restart yb-collect_metrics.timer,
            /bin/systemctl enable yb-collect_metrics.timer,
            /bin/systemctl disable yb-collect_metrics.timer,
            /bin/systemctl start yb-zip_purge_yb_logs,
            /bin/systemctl stop yb-zip_purge_yb_logs,
            /bin/systemctl restart yb-zip_purge_yb_logs,
            /bin/systemctl enable yb-zip_purge_yb_logs,
            /bin/systemctl disable yb-zip_purge_yb_logs,
            /bin/systemctl start yb-clean_cores,
            /bin/systemctl stop yb-clean_cores,
            /bin/systemctl restart yb-clean_cores,
            /bin/systemctl enable yb-clean_cores,
            /bin/systemctl disable yb-clean_cores,
            /bin/systemctl start yb-collect_metrics,
            /bin/systemctl stop yb-collect_metrics,
            /bin/systemctl restart yb-collect_metrics,
            /bin/systemctl enable yb-collect_metrics,
            /bin/systemctl disable yb-collect_metrics,
            /bin/systemctl daemon-reload'
      create: yes
      state: present
      mode: 0440
      validate: 'visudo -cf %s'

  - name: Set includedir in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"

  # Adding systemd service files for yb-master and yb-tserver
  - name: Add yb-master.service
    template:
      src: yb-master.service
      dest: "/etc/systemd/system/yb-master.service"
      owner: "{{ user_name }}"
      mode: 0644

  - name: Add yb-tserver.service
    template:
      src: yb-tserver.service
      dest: "/etc/systemd/system/yb-tserver.service"
      owner: "{{ user_name }}"
      mode: 0644

  # Adding systemd service and timer files for zip_purge_yb_logs
  - name: Add yb-zip_purge_yb_logs.service
    template:
      src: yb-zip_purge_yb_logs.service
      dest: "/etc/systemd/system/yb-zip_purge_yb_logs.service"
      owner: "{{ user_name }}"
      mode: 0644

  - name: Add yb-zip_purge_yb_logs.timer
    template:
      src: yb-zip_purge_yb_logs.timer
      dest: "/etc/systemd/system/yb-zip_purge_yb_logs.timer"
      owner: "{{ user_name }}"
      mode: 0644

  # Adding systemd service and timer files for clean_cores
  - name: Add yb-clean_cores.service
    template:
      src: yb-clean_cores.service
      dest: "/etc/systemd/system/yb-clean_cores.service"
      owner: "{{ user_name }}"
      mode: 0644

  - name: Add yb-clean_cores.timer
    template:
      src: yb-clean_cores.timer
      dest: "/etc/systemd/system/yb-clean_cores.timer"
      owner: "{{ user_name }}"
      mode: 0644

  # Adding systemd service and timer files for collect_metrics
  - name: Add yb-collect_metrics.service
    template:
      src: yb-collect_metrics.service
      dest: "/etc/systemd/system/yb-collect_metrics.service"
      owner: "{{ user_name }}"
      mode: 0644

  - name: Add yb-collect_metrics.timer
    template:
      src: yb-collect_metrics.timer
      dest: "/etc/systemd/system/yb-collect_metrics.timer"
      owner: "{{ user_name }}"
      mode: 0644

  tags: systemd_upgrade
  when: systemd_option

- block:
  - name: Check if /etc/apt/apt.conf.d/20auto-upgrades exists
    stat:
      path: /etc/apt/apt.conf.d/20auto-upgrades
    register: autoupgrade_file

  - name: Reenable unattended upgrades
    raw: 'sed -i /Unattended-Upgrade/s/"0"/"1"/ /etc/apt/apt.conf.d/20auto-upgrades'
    when: autoupgrade_file.stat.exists

  - name: Check if /etc/apt/apt.conf.d/50unattended-upgrades exists
    stat:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
    register: unattendedupgrade_file

  - name: Disable automatic reboot
    lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      line: Unattended-Upgrade::Automatic-Reboot "false";
    when: unattendedupgrade_file.stat.exists
  when: ansible_distribution == "Ubuntu"
  tags: yb-prebuilt-ami
