name: yugabyted
description: Create a yugabyted issue.
title: "[yugabyted] Title"
labels: ["area/ecosystem", "area/ybd", "status/awaiting-triage"]
body:
- type: textarea
  id: yugabyted
  attributes:
    label: Description
    placeholder: |
      **Provide a detailed description of the issue you want to report with the yugabyted based deployments.**

      **Include the steps to reproduce the issue.**
  validations:
    required: true
