defaultMarkdownHandler = "goldmark"

[goldmark]
  [goldmark.extensions]
    typographer = false
  [goldmark.parser]
    autoHeadingIDType = "blackfriday"
  [goldmark.renderer]
    unsafe = true
[tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
