# Top header menu
[[top_nav]]
  name = "Join us on"
  weight = 1
  url = "https://communityinviter.com/apps/yugabyte-db/register"
  post = "<img id='slack-logo' width='80' height='30' src='/images/slack-logo-full.svg' alt='YugabyteDB Community Slack' />"
  [top_nav.params]
    newTab = true

[[top_nav]]
  name = "Star us on"
  weight = 2
  url = "https://github.com/yugabyte/yugabyte-db"
  post = "<i class='fab fa-github'></i>"
  [top_nav.params]
    newTab = true

[[top_nav]]
  name = "Get Started"
  weight = 3
  url = "https://download.yugabyte.com"
  [top_nav.params]
    newTab = true

# Secondary header menu
[[main]]
  name = "Documentation"
  weight = 1
  identifier = "documentation"
  url = "/"

[[main]]
  name = "Docs Home"
  weight = 1
  url = "/"
  parent = "documentation"

[[main]]
  name = "Quick Start"
  weight = 3
  url = "/quick-start-yugabytedb-managed/"
  parent = "documentation"

[[main]]
  name = "Explore"
  weight = 4
  url = "/explore/"
  parent = "documentation"

[[main]]
  name = "Develop"
  weight = 5
  url = "/develop/"
  parent = "documentation"

[[main]]
  name = "Migrate"
  weight = 6
  url = "/migrate/"
  parent = "documentation"

[[main]]
  name = "Launch and Manage"
  weight = 7
  url = "/deploy/"
  parent = "documentation"

[[main]]
  name = "Benchmark"
  weight = 8
  url = "/benchmark/"
  parent = "documentation"

[[main]]
  name = "Secure"
  weight = 9
  url = "/secure/"
  parent = "documentation"

[[main]]
  name = "Troubleshoot"
  weight = 10
  url = "/migrate/"
  parent = "documentation"

[[main]]
  name = "View all products"
  weight = 11
  identifier = "view-all-products"
  parent = "documentation"

[[main]]
  name = "YugabyteDB Anywhere"
  weight = 1
  parent = "view-all-products"

[[main]]
  name = "YugabyteDB Managed"
  weight = 2
  parent = "view-all-products"

[[main]]
  name = "FAQ"
  weight = 3
  url = "/faq/"

[[main]]
  name = "Release Notes"
  weight = 4
  url = "/releases/"

# Bottom menu for left navigation
[[leftbottom]]
  name = "Contact Support"
  weight = 1
  pre = "<i class='fa fa-headset'></i>"
  url = "https://support.yugabyte.com/hc/en-us"
  [leftbottom.params]
    newTab = true

[[leftbottom]]
  name = "Join our community"
  weight = 2
  identifier = "join-our-community"
  pre = "<i class='fa fa-hands-helping'></i>"
  post = "<i></i>"

[[leftbottom]]
  name = "Slack"
  weight = 1
  parent = "join-our-community"
  pre = "<i class='fab fa-slack'></i>"
  url = "https://communityinviter.com/apps/yugabyte-db/register"
  post = "<i></i>"
  [leftbottom.params]
    newTab = true

[[leftbottom]]
  name = "GitHub"
  weight = 2
  parent = "join-our-community"
  pre = "<i class='fab fa-github'></i>"
  url = "https://github.com/yugabyte/yugabyte-db"
  [leftbottom.params]
    newTab = true

[[leftbottom]]
  name = "Forum"
  weight = 3
  parent = "join-our-community"
  pre = "<i class='fa fa-question-circle'></i>"
  url = "https://forum.yugabyte.com/"
  [leftbottom.params]
    newTab = true

[[leftbottom]]
  name = "Yugabyte Friday Tech Talks"
  weight = 4
  parent = "join-our-community"
  pre = "<i class='fa fa-phone-volume'></i>"
  url = "https://www.yugabyte.com/yftt/"
  [leftbottom.params]
    newTab = true

# Menus for preview
[[preview]]
  name = "Docs Home"
  weight = 1
  identifier = "home"
  url = "/"
  [preview.params]
    section = true

[[preview]]
  name = "Quick Start"
  weight = 3
  identifier = "quick-start"
  url = "/preview/quick-start-yugabytedb-managed/"
  [preview.params]
    section = true

[[preview]]
  name = "Explore"
  weight = 4
  identifier = "explore"
  url = "/preview/explore/"
  [preview.params]
    section = true

[[preview]]
  name = "Develop"
  weight = 5
  identifier = "develop"
  url = "/preview/develop/"
  [preview.params]
    section = true

[[preview]]
  name = "Migrate"
  weight = 6
  identifier = "migrate"
  url = "/preview/migrate/"
  [preview.params]
    section = true

[[preview]]
  name = "Launch and Manage"
  weight = 7
  identifier = "launch-and-manage"
  [preview.params]
    section = true

[[preview]]
  name = "Benchmark"
  weight = 8
  identifier = "benchmark"
  url = "/preview/benchmark/"
  [preview.params]
    section = true

[[preview]]
  name = "Secure"
  weight = 9
  identifier = "secure"
  url = "/preview/secure/"
  [preview.params]
    section = true

[[preview]]
  name = "Troubleshoot"
  weight = 10
  identifier = "troubleshoot"
  url = "/preview/troubleshoot/"
  [preview.params]
    section = true

[[preview]]
  name = "View all products"
  weight = 11
  identifier = "view-all-products"
  [preview.params]
    section = true

[[preview]]
  name = "YugabyteDB Anywhere"
  weight = 1
  identifier = "yugabytedb-anywhere"
  parent = "view-all-products"
	url = "/preview/yugabyte-platform/overview/"
  [preview.params]
    section = true

[[preview]]
  name = "YugabyteDB Managed"
  weight = 2
  identifier = "yugabytedb-managed"
  parent = "view-all-products"
	url = "/preview/yugabyte-cloud/cloud-overview/"
  [preview.params]
    section = true

[[preview_releases]]
  name = "Releases"
  weight = 1
  identifier = "release-notes"
  [preview_releases.params]
    section = true
    hideLink = true

[[preview_faq]]
  name = "FAQ"
  weight = 2
  identifier = "faq"
  [preview_faq.params]
    section = true
    hideLink = true

# Menus for stable
[[stable]]
  name = "Docs Home"
  weight = 1
  identifier = "home"
  url = "/"
  [stable.params]
    section = true

[[stable]]
  name = "Quick Start"
  weight = 3
  identifier = "quick-start"
  url = "/stable/quick-start-yugabytedb-managed/"
  [stable.params]
    section = true

[[stable]]
  name = "Explore"
  weight = 4
  identifier = "explore"
  url = "/stable/explore/"
  [stable.params]
    section = true

[[stable]]
  name = "Develop"
  weight = 5
  identifier = "develop"
  url = "/stable/develop/"
  [stable.params]
    section = true

[[stable]]
  name = "Migrate"
  weight = 6
  identifier = "migrate"
  url = "/stable/migrate/"
  [stable.params]
    section = true

[[stable]]
  name = "Launch and Manage"
  weight = 7
  identifier = "launch-and-manage"
  [stable.params]
    section = true

[[stable]]
  name = "Benchmark"
  weight = 8
  identifier = "benchmark"
  url = "/stable/benchmark/"
  [stable.params]
    section = true

[[stable]]
  name = "Secure"
  weight = 9
  identifier = "secure"
  url = "/stable/secure/"
  [stable.params]
    section = true

[[stable]]
  name = "Troubleshoot"
  weight = 10
  identifier = "troubleshoot"
  url = "/stable/troubleshoot/"
  [stable.params]
    section = true

[[stable]]
  name = "View all products"
  weight = 11
  identifier = "view-all-products"
  [stable.params]
    section = true

[[stable]]
  name = "YugabyteDB Anywhere"
  weight = 1
  identifier = "yugabytedb-anywhere"
  parent = "view-all-products"
	url = "/stable/yugabyte-platform/overview/"
  [stable.params]
    section = true

[[stable]]
  name = "YugabyteDB Managed"
  weight = 2
  identifier = "yugabytedb-managed"
  parent = "view-all-products"
	url = "/stable/yugabyte-cloud/cloud-overview/"
  [stable.params]
    section = true

[[stable_releases]]
  name = "Releases"
  identifier = "release-notes"
  [stable_releases.params]
    section = true
    hideLink = true

[[stable_faq]]
  name = "FAQ"
  identifier = "faq"
  [stable_faq.params]
    section = true
    hideLink = true

# Menus for v2.8
[["v2.8"]]
  name = "Docs Home"
  weight = 1
  identifier = "home"
  url = "/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "Quick Start"
  weight = 3
  identifier = "quick-start"
  url = "/v2.8/quick-start-yugabytedb-managed/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "Explore"
  weight = 4
  identifier = "explore"
  url = "/v2.8/explore/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "Develop"
  weight = 5
  identifier = "develop"
  url = "/v2.8/develop/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "Migrate"
  weight = 6
  identifier = "migrate"
  url = "/v2.8/migrate/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "Launch and Manage"
  weight = 7
  identifier = "launch-and-manage"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "Benchmark"
  weight = 8
  identifier = "benchmark"
  url = "/v2.8/benchmark/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "Secure"
  weight = 9
  identifier = "secure"
  url = "/v2.8/secure/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "Troubleshoot"
  weight = 10
  identifier = "troubleshoot"
  url = "/v2.8/troubleshoot/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "View all products"
  weight = 11
  identifier = "view-all-products"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "YugabyteDB Anywhere"
  weight = 1
  identifier = "yugabytedb-anywhere"
  parent = "view-all-products"
	url = "/v2.8/yugabyte-platform/overview/"
  ["v2.8".params]
    section = true

[["v2.8"]]
  name = "YugabyteDB Managed"
  weight = 2
  identifier = "yugabytedb-managed"
  parent = "view-all-products"
	url = "/v2.8/yugabyte-cloud/cloud-overview/"
  ["v2.8".params]
    section = true

[["v2.8_releases"]]
  name = "Releases"
  identifier = "release-notes"
  ["v2.8_releases".params]
    section = true
    hideLink = true

[["v2.8_faq"]]
  name = "FAQ"
  identifier = "faq"
  ["v2.8_faq".params]
    section = true
    hideLink = true

# Menus for v2.6
[["v2.6"]]
  name = "Docs Home"
  weight = 1
  identifier = "home"
  url = "/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Quick Start"
  weight = 3
  identifier = "quick-start"
  url = "/v2.6/quick-start-yugabytedb-managed/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Explore"
  weight = 4
  identifier = "explore"
  url = "/v2.6/explore/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Develop"
  weight = 5
  identifier = "develop"
  url = "/v2.6/develop/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Migrate"
  weight = 6
  identifier = "migrate"
  url = "/v2.6/migrate/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Launch and Manage"
  weight = 7
  identifier = "launch-and-manage"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Benchmark"
  weight = 8
  identifier = "benchmark"
  url = "/v2.6/benchmark/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Secure"
  weight = 9
  identifier = "secure"
  url = "/v2.6/secure/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Troubleshoot"
  weight = 10
  identifier = "troubleshoot"
  url = "/v2.6/troubleshoot/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "View all products"
  weight = 11
  identifier = "view-all-products"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "YugabyteDB Anywhere"
  weight = 1
  identifier = "yugabytedb-anywhere"
  parent = "view-all-products"
	url = "/v2.6/yugabyte-platform/overview/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "YugabyteDB Managed"
  weight = 2
  identifier = "yugabytedb-managed"
  parent = "view-all-products"
	url = "/v2.6/yugabyte-cloud/cloud-overview/"
  ["v2.6".params]
    section = true

[["v2.6_releases"]]
  name = "Releases"
  identifier = "release-notes"
  ["v2.6_releases".params]
    section = true
    hideLink = true

[["v2.6_faq"]]
  name = "FAQ"
  identifier = "faq"
  ["v2.6_faq".params]
    section = true
    hideLink = true

# Menus for v2.4
[["v2.4"]]
  name = "Docs Home"
  weight = 1
  identifier = "home"
  url = "/"
  ["v2.4".params]
    section = true

[["v2.4"]]
  name = "Quick Start"
  weight = 3
  identifier = "quick-start"
  url = "/v2.4/quick-start-yugabytedb-managed/"
  ["v2.4".params]
    section = true

[["v2.4"]]
  name = "Explore"
  weight = 4
  identifier = "explore"
  url = "/v2.4/explore/"
  ["v2.4".params]
    section = true

[["v2.4"]]
  name = "Develop"
  weight = 5
  identifier = "develop"
  url = "/v2.4/develop/"
  ["v2.4".params]
    section = true

[["v2.4"]]
  name = "Migrate"
  weight = 6
  identifier = "migrate"
  url = "/v2.4/migrate/"
  ["v2.4".params]
    section = true

[["v2.4"]]
  name = "Launch and Manage"
  weight = 7
  identifier = "launch-and-manage"
  ["v2.4".params]
    section = true

[["v2.6"]]
  name = "Benchmark"
  weight = 8
  identifier = "benchmark"
  url = "/v2.6/benchmark/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Secure"
  weight = 9
  identifier = "secure"
  url = "/v2.6/secure/"
  ["v2.6".params]
    section = true

[["v2.6"]]
  name = "Troubleshoot"
  weight = 10
  identifier = "troubleshoot"
  url = "/v2.6/troubleshoot/"
  ["v2.6".params]
    section = true

[["v2.4"]]
  name = "View all products"
  weight = 11
  identifier = "view-all-products"
  ["v2.4".params]
    section = true

[["v2.4"]]
  name = "YugabyteDB Anywhere"
  weight = 1
  identifier = "yugabytedb-anywhere"
  parent = "view-all-products"
	url = "/v2.4/yugabyte-platform/overview/"
  ["v2.4".params]
    section = true

[["v2.4"]]
  name = "YugabyteDB Managed"
  weight = 2
  identifier = "yugabytedb-managed"
  parent = "view-all-products"
	url = "/v2.4/yugabyte-cloud/cloud-overview/"
  ["v2.4".params]
    section = true

[["v2.4_releases"]]
  name = "Releases"
  identifier = "release-notes"
  ["v2.4_releases".params]
    section = true
    hideLink = true

[["v2.4_faq"]]
  name = "FAQ"
  identifier = "faq"
  ["v2.4_faq".params]
    section = true
    hideLink = true
