# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: Validate server type
  hosts: localhost
  gather_facts: no
  tasks:
    - assert:
        that:
          - server_type is defined
          - server_type in ["cluster-server"]

# This is required to install backup utils using python setup scripts
- name: Install Python on Ubuntu
  hosts: "{{ instance_search_pattern }}"
  gather_facts: yes
  pre_tasks:
    - name: Verify and Install Python
      raw: >
        bash -c "test -e /usr/bin/python ||
        (sudo apt -qqy update && sudo apt install -qqy python-minimal)"
      when: ansible_distribution == "Ubuntu"

- name: Provision server
  become: yes
  become_method: sudo
  hosts: "{{ instance_search_pattern }}"
  roles:
    - "provision-{{ server_type }}"
  vars_files:
    - "{{ vars_file | default(placeholder_vars_file) }}"
