apiVersion: operator.yugabyte.io/v1alpha1
kind: YBUniverse
metadata:
  name: universe-cr
spec:
  numNodes: 3
  replicationFactor: 3
  instanceType: dev
  assignPublicIP: true
  useTimeSync: true
  enableYSQL: true
  enableYEDIS: false
  enableNodeToNodeEncrypt: true
  enableClientToNodeEncrypt: true
  enableVolumeEncryption: false
  ybSoftwareVersion: 2.17.1.0-b439
  enableYSQLAuth: true
  ysqlPassword: Test123!
  enableYCQL: true
  enableYCQLAuth: true
  ycqlPassword: Test123!
  enableIPV6: false
  enableExposingService: NONE
  accessKeyCode: ''
  useSystemd: true
  dedicatedNodes: false
