apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ybuniverses.operator.yugabyte.io
spec:
  group: operator.yugabyte.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # replicas:
                #   type: integer
                #   x-kubernetes-validations:
                #   - message: Value is immutable
                #     rule: self == oldSelf
                universeName:
                  type: string
                numNodes:
                  type: integer
                replicationFactor:
                  type: integer
                instanceType:
                  type: string
                assignPublicIP:
                  type: boolean
                useTimeSync:
                  type: boolean
                enableYSQL:
                  type: boolean
                enableYEDIS:
                  type: boolean
                enableNodeToNodeEncrypt:
                  type: boolean
                enableClientToNodeEncrypt:
                  type: boolean
                enableVolumeEncryption:
                  type: boolean
                ybSoftwareVersion:
                  type: string
                providerName:
                  type: string
                enableYSQLAuth:
                  type: boolean
                ysqlPassword:
                  type: string
                enableYCQL:
                  type: boolean
                enableYCQLAuth:
                  type: boolean
                ycqlPassword:
                  type: string
                enableIPV6:
                  type: boolean
                enableExposingService:
                  type: string
                accessKeyCode:
                  type: string
                replicationFactor:
                  type: integer
                useSystemd:
                  type: boolean
                dedicatedNodes:
                  type: boolean
            status:
              type: object
              properties:
                universeStatus:
                  type: string
      subresources:
        status: {}
  names:
    kind: YBUniverse
    plural: ybuniverses
    singular: ybuniverse
    shortNames:
      - ybuniverse
  scope: Namespaced
