/private/runtime_config:
  parameters:
      - name: scopeId
        in: query
        description: ID of the scope for whose runtime config the operations are to be done
        required: false
        style: form
        explode: false
        schema:
          type: string
          format: uuid
      - name: scopeType
        in: query
        description: Scope type of the scopeId
        required: true
        style: form
        explode: false
        schema:
          type: string
          enum: [GLOBAL, ACCOUNT]
  put:
    description: Update or delete configuration keys for given scope.
    tags:
      - internal-runtime-config
    summary: Update configuration keys for given scope.
    operationId: updateRuntimeConfig
    requestBody:
      $ref: '../request_bodies/_index.yaml#/RuntimeConfigUpdateRequest'
    responses:
      '200':
        $ref: '../responses/_index.yaml#/RuntimeConfigUpdateResponse'
      '400':
        $ref: '../responses/_index.yaml#/ApiError'
      '500':
        $ref: '../responses/_index.yaml#/ApiError'
  get:
    description: Get runtime configuration
    operationId: getRuntimeConfig
    summary: Get runtime configuration
    tags:
      - internal-runtime-config
    responses:
      '200':
        $ref: '../responses/_index.yaml#/RuntimeConfigResponse'
      '400':
        $ref: '../responses/_index.yaml#/ApiError'
      '500':
        $ref: '../responses/_index.yaml#/ApiError'
