'/public/accounts/{accountId}/projects':
  get:
    description: List projects
    tags:
      - project
    summary: List projects
    operationId: listProjects
    parameters:
      - name: accountId
        in: path
        description: ID of the account
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: name
        in: query
        description: Filter projects by name
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: order
        in: query
        description: Order of results
        required: false
        style: form
        explode: false
        schema:
          type: string
          default: asc
      - name: order_by
        in: query
        description: Sort results by attribute
        required: false
        style: form
        explode: false
        schema:
          type: string
          default: name
      - name: limit
        in: query
        description: Limit number of results returned per page
        required: false
        style: form
        explode: false
        schema:
          type: integer
          default: 25
          minimum: 1
          maximum: 100
      - name: continuation_token
        in: query
        description: Boundary before next page
        required: false
        style: form
        explode: false
        schema:
          type: string
    responses:
      '200':
        $ref: '../responses/_index.yaml#/ProjectListResponse'
      '400':
        $ref: '../responses/_index.yaml#/ApiError'
      '500':
        $ref: '../responses/_index.yaml#/ApiError'
  post:
    description: Create a project
    tags:
      - project
    summary: Create a project
    operationId: createProject
    parameters:
      - name: accountId
        in: path
        description: ID of account to add the project to
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
    requestBody:
      $ref: '../request_bodies/_index.yaml#/CreateProjectRequest'
    responses:
      '200':
        $ref: '../responses/_index.yaml#/ProjectResponse'
      '400':
        $ref: '../responses/_index.yaml#/ApiError'
      '500':
        $ref: '../responses/_index.yaml#/ApiError'
  parameters:
    - schema:
        type: string
      name: accountId
      in: path
      required: true
'/public/accounts/{accountId}/projects/{projectId}':
  get:
    description: Get a project
    tags:
      - project
    summary: Get project info
    operationId: getProject
    parameters:
      - name: accountId
        in: path
        description: ID of the associated account
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: projectId
        in: path
        description: ID of project to get
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
    responses:
      '200':
        $ref: '../responses/_index.yaml#/ProjectResponse'
      '400':
        $ref: '../responses/_index.yaml#/ApiError'
      '500':
        $ref: '../responses/_index.yaml#/ApiError'
  parameters:
    - schema:
        type: string
      name: accountId
      in: path
      required: true
    - schema:
        type: string
      name: projectId
      in: path
      required: true
  delete:
    description: Delete a project
    tags:
      - project
    summary: Delete project
    operationId: deleteProject
    parameters:
      - name: accountId
        in: path
        description: ID of the associated account
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: projectId
        in: path
        description: ID of project to get
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
    responses:
      '200':
        description: Project successfully deleted
      '400':
        $ref: '../responses/_index.yaml#/ApiError'
      '500':
        $ref: '../responses/_index.yaml#/ApiError'
